package com.commodity.commons;

public enum ContractState {

	ACTIVE,SENT_TO_BUYER,SENT_TO_BANK_BUYER,ACCEPTED_BANK_BUYER,REJECTED_BANK_BUYER,
    SENT_TO_BANK_SELLER,ACCEPTED_BANK_SELLER,REJECTED_BANK_SELLER
}
